export type Ids = { [string]: number }

return {
	Joined = 0,
	Escaped = 0,
	Escapes = {
		Count = 3,
		Badge = 0,
	},

	Rooms = {
		["Bell"] = 4473544452205351,
		["Chairs"] = 4117956425584522,
		["Circle Bridge"] = 980945573649633,
		["Endless Bridges"] = 882227390310478,
		["Endless Paintings"] = 4110176206537729,
		["Endless Pillars"] = 0,
		["Endless Room"] = 0,
		["Endless Stairs"] = 0,
		["Floating"] = 0,
		["Glitched Hallway"] = 0,
		["Hallway"] = 0,
		["Hallways"] = 0,
		["Mess"] = 0,
		["Mirror"] = 0,
		["Paintings"] = 0,
		["Pendulum"] = 0,
		["Pit"] = 0,
		["Pool"] = 0,
		["Rooms"] = 0,
		["Stairs"] = 0,
		["The Garden"] = 0,
		["The Hole"] = 0,
	} :: Ids,

	Computers = {
		Blue = 0,
		Red = 0,
		Green = 0,
		Yellow = 0,
		Purple = 0,
	} :: Ids,

	Deaths = {
		Stalker = 0,
		CeilingDweller = 0,
		Mimic = 0,
		Chaser = 0,
	} :: Ids,

	Icon = {
		Retries = 3,
		RetryDelay = 2,
		PrefetchGap = 0.1,
	},
}
