return {
	LightRange = 80,
	ConnectedHallwayLightRange = 15,
	DarkDistance = 40,

	TurnRate = 16,

	BackdropDistance = 8,
	BackdropMinimumDistance = 5,
	BackdropEndMargin = 10,
	BackdropCeilingSearch = 60,
	BackdropHeightOverlap = 1.5,
	BackdropMinimumHeight = 8,
	BackdropHeight = 24,
	BackdropThickness = 1,

	DistortionSpeed = 48,

	EyeColors = {
		Color3.fromRGB(190, 12, 12),
		Color3.fromRGB(255, 138, 0),
		Color3.fromRGB(226, 224, 96),
		Color3.fromRGB(80, 235, 130),
		Color3.fromRGB(150, 70, 255),
		Color3.fromRGB(235, 240, 255),
	},

	PairSpacing = 2.6,

	PairPlacementTries = 16,

	Variants = {
		{
			Weight = 5,
			PairsMin = 1,
			PairsMax = 1,
		},
	},
}
