local TopbarConfig = {
	PageGroup = "Main",
	Alignment = "Left",
	ImageScale = 0.65,
	Icons = {
		{
			PageId = "Index",
			Name = "Index",
			Label = "Index",
			Image = "rbxassetid://85599708365548",
			Order = 1,
		},
		{
			PageId = "Gems",
			Name = "Gems",
			Label = "Gems",
			Image = "rbxassetid://121669763562417",
			Order = 2,
		},
		{
			PageId = "Gallery",
			Name = "Gallery",
			Label = "Gallery",
			Image = "rbxassetid://72860916802925",
			Order = 3,
		},
	},
}

return TopbarConfig
