local TopbarConfig = {
	PageGroup = "Main",
	Alignment = "Left",
	ImageScale = 0.65,
	Icons = {
		{
			PageId = "Index",
			Name = "Index",
			Label = "Index",
			Image = "rbxassetid://77630182224034",
			Order = 1,
		},
		{
			PageId = "Gems",
			Name = "Gems",
			Label = "Gems",
			Image = "rbxassetid://75007149827110",
			Order = 2,
		},
		{
			PageId = "Gallery",
			Name = "Gallery",
			Label = "Gallery",
			Image = "rbxassetid://133693983228131",
			Order = 3,
		},
	},
}

return TopbarConfig
